// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYPrFCr-NNoov9QtIoAitKj6eR40mnu4',
    appId: '1:239757356974:web:f6b2b57c584b71a4a1223f',
    messagingSenderId: '239757356974',
    projectId: 'flutter-3a53f',
    authDomain: 'flutter-3a53f.firebaseapp.com',
    databaseURL: 'https://flutter-3a53f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-3a53f.appspot.com',
    measurementId: 'G-1GT6ZZ9HT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUgOLvJS5hXZiXJhmkbWabYKKLBQl9sO4',
    appId: '1:239757356974:android:94ce5e96872f3771a1223f',
    messagingSenderId: '239757356974',
    projectId: 'flutter-3a53f',
    databaseURL: 'https://flutter-3a53f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-3a53f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1d0YFSG5cdeOIbhGF1pMLbNXExAxLq-0',
    appId: '1:239757356974:ios:3893b295103d2d1ba1223f',
    messagingSenderId: '239757356974',
    projectId: 'flutter-3a53f',
    databaseURL: 'https://flutter-3a53f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-3a53f.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1d0YFSG5cdeOIbhGF1pMLbNXExAxLq-0',
    appId: '1:239757356974:ios:1c314a5f2b70d32ca1223f',
    messagingSenderId: '239757356974',
    projectId: 'flutter-3a53f',
    databaseURL: 'https://flutter-3a53f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-3a53f.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
